config/routes.rb
JacksongarietyDev::Application.routes.draw do
  # Active Admin

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  mount Ckeditor::Engine => '/ckeditor'

  # Pages

  root :to => "home#index"

  match "/home" => redirect("/#")

  match "/journals" => redirect("/#journals")

  match "/photography" => redirect("/#photography")

  match "/thoughts" => redirect("/#thoughts")

  match "/projects" => redirect("/#projects")

  match '/resume' => "pages#resume"
  
  match '/contact' => "pages#resume"
  
  match '/about' => "pages#resume"

  match '/feeds' => "pages#feeds"
  
  match '/goals' => "pages#goals"

  # RSS feeds

  match '/feeds/literary' => 'posts#index', :as => :feed, :defaults => { :format => 'atom' }

  match '/feeds/architect' => 'home#architect', :as => :feed, :defaults => { :format => 'atom' }

  match '/feed' => 'home#architect', :as => :feed, :defaults => { :format => 'atom' }

  match '/feed.rss' => 'home#architect', :as => :feed, :defaults => { :format => 'atom' }

  match '/feeds/stalker' => 'home#index', :as => :feed, :defaults => { :format => 'atom' }

  # Models

  resources :projects

  resources :events

  resources :photographs, :path => "photography"

  resources :quotes, :path => "thoughts"

  resources :videos

  resources :posts, :path => "journals"

  # Methods

  match "like", :to => "posts#like"
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  just_define_datetime_picker :created_at, :add_to_attr_accessible => true

  attr_accessible :content, :date, :slug, :author

  def to_param
    "#{slug}"
  end

  validates :content, :author, :slug, :presence => true
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quotes }
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @quote = Quote.find_by_slug(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/new
  # GET /quotes/new.json
  def new
    @quote = Quote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/1/edit
  def edit
    @quote = Quote.find_by_slug(params[:id])
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(params[:quote])

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render json: @quote, status: :created, location: @quote }
      else
        format.html { render action: "new" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quotes/1
  # PUT /quotes/1.json
  def update
    @quote = Quote.find_by_slug(params[:id])

    respond_to do |format|
      if @quote.update_attributes(params[:quote])
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote = Quote.find_by_slug(params[:id])
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<h1>Listing quotes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Date</th>
    <th>Slug</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @quotes.each do |quote| %>
  <tr>
    <td><%= quote.title %></td>
    <td><%= quote.content %></td>
    <td><%= quote.date %></td>
    <td><%= quote.slug %></td>
    <td><%= link_to 'Show', quote %></td>
    <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
    <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<% content_for :title, truncate(@quote.content, :length => 50) + " — " + @quote.author %>

<section>
  <p id="notice"><%= notice %></p>

  <article>
    <p>"<%= @quote.content %>"</p>
    <p class="author">&mdash; <%= @quote.author %></p>
  </article>
<section>