config/routes.rb
JacksongarietyDev::Application.routes.draw do
  # Active Admin

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  mount Ckeditor::Engine => '/ckeditor'

  # Pages

  root :to => "home#index"

  match "/home" => redirect("/#")

  match "/journals" => redirect("/#journals")

  match "/photography" => redirect("/#photography")

  match "/thoughts" => redirect("/#thoughts")

  match "/projects" => redirect("/#projects")

  match '/resume' => "pages#resume"
  
  match '/contact' => "pages#resume"
  
  match '/about' => "pages#resume"

  match '/feeds' => "pages#feeds"
  
  match '/goals' => "pages#goals"

  # RSS feeds

  match '/feeds/literary' => 'posts#index', :as => :feed, :defaults => { :format => 'atom' }

  match '/feeds/architect' => 'home#architect', :as => :feed, :defaults => { :format => 'atom' }

  match '/feed' => 'home#architect', :as => :feed, :defaults => { :format => 'atom' }

  match '/feed.rss' => 'home#architect', :as => :feed, :defaults => { :format => 'atom' }

  match '/feeds/stalker' => 'home#index', :as => :feed, :defaults => { :format => 'atom' }

  # Models

  resources :projects

  resources :events

  resources :photographs, :path => "photography"

  resources :quotes, :path => "thoughts"

  resources :videos

  resources :posts, :path => "journals"

  # Methods

  match "like", :to => "posts#like"
end

app/models/video.rb
class Video < ActiveRecord::Base
  just_define_datetime_picker :created_at, :add_to_attr_accessible => true

  attr_accessible :date, :description, :slug, :title, :vimeo

  validates :vimeo, :title, :presence => true
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :vimeo %><br />
    <%= f.text_field :vimeo %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :thumb %><br />
    <%= f.text_field :thumb %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Vimeo</th>
    <th>Date</th>
    <th>Slug</th>
    <th>Thumb</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @videos.each do |video| %>
  <tr>
    <td><%= video.title %></td>
    <td><%= video.description %></td>
    <td><%= video.vimeo %></td>
    <td><%= video.date %></td>
    <td><%= video.slug %></td>
    <td><%= video.thumb %></td>
    <td><%= link_to 'Show', video %></td>
    <td><%= link_to 'Edit', edit_video_path(video) %></td>
    <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<%=h content_for(:title, @video.title + " — Jackson Gariety") %>

<section>
  <p id="notice"><%= notice %></p>

  <p>
    <b>Title:</b>
    <%= @video.title %>
  </p>

  <p>
    <b>Description:</b>
    <%= @video.description %>
  </p>

  <p>
    <b>Vimeo:</b>
    <%= @video.vimeo %>
  </p>

  <p>
    <b>Date:</b>
    <%= @video.date %>
  </p>

  <p>
    <b>Slug:</b>
    <%= @video.slug %>
  </p>

  <p>
    <b>Thumb:</b>
    <%= @video.thumb %>
  </p>
</section>