config/routes.rb
JacksongarietyDev::Application.routes.draw do
  # Active Admin

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  mount Ckeditor::Engine => '/ckeditor'

  # Pages

  root :to => "home#index"

  match "/home" => redirect("/#")

  match "/journals" => redirect("/#journals")

  match "/photography" => redirect("/#photography")

  match "/thoughts" => redirect("/#thoughts")

  match "/projects" => redirect("/#projects")

  match '/resume' => "pages#resume"
  
  match '/contact' => "pages#resume"
  
  match '/about' => "pages#resume"

  match '/feeds' => "pages#feeds"
  
  match '/goals' => "pages#goals"

  # RSS feeds

  match '/feeds/literary' => 'posts#index', :as => :feed, :defaults => { :format => 'atom' }

  match '/feeds/architect' => 'home#architect', :as => :feed, :defaults => { :format => 'atom' }

  match '/feed' => 'home#architect', :as => :feed, :defaults => { :format => 'atom' }

  match '/feed.rss' => 'home#architect', :as => :feed, :defaults => { :format => 'atom' }

  match '/feeds/stalker' => 'home#index', :as => :feed, :defaults => { :format => 'atom' }

  # Models

  resources :projects

  resources :events

  resources :photographs, :path => "photography"

  resources :quotes, :path => "thoughts"

  resources :videos

  resources :posts, :path => "journals"

  # Methods

  match "like", :to => "posts#like"
end

app/models/post.rb
class Post < ActiveRecord::Base
  just_define_datetime_picker :created_at, :add_to_attr_accessible => true

  attr_accessible :content, :date, :slug, :thumb, :title

  has_attached_file :thumb,
                    :styles => {
                      :large => "660x660>",
                      :medium => "330x330>",
                      :small => "150x150>"
                    }

  def to_param
    "#{slug}"
  end

  validates :title, :content, :thumb, :slug, :presence => true
  
  def next_path
    self.class.where(["created_at < ?", created_at]).last || self.class.last
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @title = "Jackson Gariety - The Literary"

    @posts = Post.all

    @updated = @posts.first.updated_at unless @posts.empty?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.atom { render :layout => false } # index.atom.builder
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_by_slug(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find_by_slug(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find_by_slug(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find_by_slug(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def like
    render :nothing => true

    id = params[:post_id]
    cookies.permanent[:like_history] = "" unless cookies[:like_history]

    unless cookies[:like_history].split(",").include? id.to_s

      cookies.permanent[:like_history] = cookies[:like_history] + ",#{id}"

      @post = Post.find(id)

      @post.update_column(:likes, @post.likes + 1)
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :thumb %><br />
    <%= f.file_field :thumb %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Date</th>
    <th>Slug</th>
    <th>Thumb</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= post.date %></td>
    <td><%= post.slug %></td>
    <td><%= post.thumb %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/show.html.erb
<% content_for :title, @post.title + " by Jackson Gariety" %>
<% content_for :description, @post.content.split("\n\n", 2)[0] %>
<% content_for :hashtraffic, "<script src=\"http://hashtag.ly/js/hashtraffic-desktop.js\" type=\"text/javascript\"></script>".html_safe %>

<%
  url = request.protocol + request.host_with_port + request.fullpath
  (clicked = (cookies[:like_history].include? @post.id.to_s) ? " clicked" : "") if cookies[:like_history]
%>

<section>
  <p id="notice"><%= notice %></p>

  <h1><%= @post.title %></h1>

  <article class="post-content">
    <p class="crafted-on"><i>Crafted on <%= @post.created_at.strftime("%A, %B #{@post.created_at.day.ordinalize}, %Y") %></i></p>
    <%= @post.content.html_safe %>
    <p><span class="dots"><% 200.times do %>&middot;<% end %></span><br></p>
    <footer>
      <div class="share">
        <%= link_to "<div class=\"heart#{clicked}\"></div>".html_safe, like_path(:post_id => @post.id), :remote => true %>
        <span class="love count"><%= @post.likes %></span>
        <span>then</span>
        <%= link_to "<div class=\"tweet\"></div>".html_safe, "https://twitter.com/intent/tweet?original_referer=#{CGI::escape(url)}&text=#{CGI::escape(@post.title)}&url=#{CGI::escape(url)}&via=JacksonGariety", :target => "_blank" %>
        <span class="twitter count">0</span>
      </div><br>
      <p>Now read: <%= link_to @post.next_path.title, @post.next_path %></p>
    </footer>
  </article>
</section>